name: Windows check

on:
  push:
    branches:
      - master
  schedule:
    - cron: "0 6 30 * *" # at 6:00 each 30th day of month

jobs:
  build_and_test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [windows-latest]
        build-type: [Debug, Release]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          submodules: "recursive"

      - name: build_and_test
        uses: ./.github/workflows/build_and_test
        with:
          build-type: ${{ matrix.build-type }}
